version = 1

test_patterns = [
  "test/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "mocha"
  ]
  style_guide = "standard"

[[transformers]]
name = "prettier"
enabled = true