version = 1

test_patterns = [
  "tests/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "mocha"
  ]

[[transformers]]
name = "prettier"
enabled = true